# config/model/bilstm_ctc_noaug.yaml
# @package _global_

module:
  _target_: emg2qwerty.bilstm_module.BiLSTMCTCModule
  in_features: 528
  mlp_features: [384]
  hidden_size: 256
  num_layers: 2
  dropout: 0.1
  bidirectional: true

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]

transforms:
  train:
    - ${to_tensor}
    - ${band_rotation}
    - ${temporal_jitter}
    - ${logspec}
  val:
    - ${to_tensor}
    - ${logspec}
  test: ${transforms.val}